name: 'Flutter Action'
description: 'Setup your runner with Flutter environment'
author: 'Alif Rachmawadi'
inputs:
  version:
    description: 'The Flutter version to make available on the path'
    required: false
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'maximize'
  color: 'blue'
