name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        channel: [stable, beta, dev]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
      with:
        channel: ${{ matrix.channel }}
    - name: Print FLUTTER_ROOT
      shell: bash
      run: echo "FLUTTER_ROOT set to $FLUTTER_ROOT"
    - name: Run dart --version
      shell: bash
      run: dart --version
    - name: Run flutter --version
      shell: bash
      run: flutter --version
